app.py
import os
from flask import Flask
from flask_migrate import Migrate
from config import DevConfig, ProdConfig
from model import db, seedData, Customer

def create_app():
	app = Flask(__name__)
	
	if os.getenv("RUNENVIRONMENT") == 'production':
		print('!!Kör i PRODUCTION MODE!!')
		app.config.from_object(ProdConfig)
	else:
		app.config.from_object(DevConfig)

	db.init_app(app)
	migrate = Migrate(app, db)

	from routes import main
	app.register_blueprint(main)

	with app.app_context():
		db.create_all()
		seedData(db)	
	return app

if __name__ == '__main__':
	app = create_app()
	app.run(debug=True)

routes.py
from flask import Blueprint, jsonify, render_template, request

from model import Customer
from app import db

main = Blueprint('main', __name__)

@main.route('/')
def view_all_customers():
	return render_template('index.html', customers=get_customer_data())

@main.route('/customer/<int:customer_id>')
def view_customer(customer_id):
	customer = Customer.query.get_or_404(customer_id)
	return render_template('customer_detail.html', customer=customer)

@main.route('/api/customer', methods=["POST"])
def apiCustomerCreate():
	data = request.get_json()
	c = Customer()
	c.city = data['city']
	c.name = data['name']
	c.telephone = data['telephone']
	c.telephoneCountryCode = data['telephoneCountryCode']
	db.session.add(c)
	db.session.commit()
	return jsonify({
		"id": c.id,
		"name": c.name,
		"city": c.city,
		"telephone": c.telephone ,
		"telephoneCountryCode": c.telephoneCountryCode,
	}), 201

@main.route('/api/customer/<id>')	
def apiCustomerRead(id):
	c = Customer.query.filter_by(id=id).first_or_404()
	return jsonify({
		"id": c.id,
		"name": c.name,
		"city": c.city,
		"telephone": c.telephone ,
		"telephoneCountryCode": c.telephoneCountryCode,
	}), 200

@main.route('/api/customer/<id>', methods=["PUT"])
def apiCustomerUpdate(id):
	data = request.get_json()
	c = Customer.query.filter_by(id=id).first_or_404()
	c.city = data['city']
	c.name = data['name']
	c.telephone = data['telephone']
	c.telephoneCountryCode = data['telephoneCountryCode']
	db.session.commit()
	return jsonify({
		"id": c.id,
		"name": c.name,
		"city": c.city,
		"telephone": c.telephone ,
		"telephoneCountryCode": c.telephoneCountryCode,
	}), 200

@main.route('/api/customer')
def apiCustomerList():
	return jsonify(get_customer_data())

def get_customer_data():
	return [
		{
			"id": c.id,
			"name": c.name,
			"city": c.city,
		}
		for c in Customer.query.all()
	]

templates/customer_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ customer.name }}</title>
</head>
<body>
    <h1>{{ customer.name }} </h1>
    <p>City: {{ customer.city }}</p>
    <p>Telephone: {{ customer.telephone }}</p>
    <p>Telephone country code: {{ customer.telephoneCountryCode }}</p>
    <a href="{{ url_for('main.view_all_customers') }}">Back to Customer List</a>
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="sv">
	<head>
		<title>Customers</title>
	</head>
</html>
<body>
	<h1>Customers</h1>
	Below is a list of all customers 
	<ul>
			{% for customer in customers %}
					<li><a href="{{ url_for('main.view_customer', customer_id=customer.id)}}">{{ customer.name }}</a></li>
			{% endfor %}
	</ul>
</body>